services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    env_file:
      - .env.local
    environment:
      DB_TYPE: sqlite
      N8N_BLOCK_ENV_ACCESS_IN_NODE: "false"
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

volumes:
  n8n_data: